enum Sorts {
    BUBBLESORT,
    COMBSORT,
    SELECTIONSORT,
    INSERTIONSORT,
    SHELLSORT,
    COCKTAILSORT,
    PANCAKESORT,
    MERGESORT,
    QUICKSORT,
    HEAPSORT,
    RADIXSORT,
    COUNTINGSORT,
    BUCKETSORT,
    INTROSORT,
    BOGOSORT,
    BOZOSORT
}
